Ability to format specific file/dir by its path
pest-parser/pest-fmt pull request #23
Opened 2023-03-11 11:55 UTC by TheAwiteb

Will fix https://github.com/pest-parser/pest-fmt/issues/21

### Changes
- Specify file or directory path, if the path is file, will format it, if its directory will format all `.pest` in it
- Print "Formatted <path>" or "Unchanged <path>" after each file in the directory, depending on whether it was formatted or not. Also with file path

2023-03-11 16:08 UTC, huacnlee commented
We don’t need to print how many files does not changed, this message not useful.

2023-03-11 16:10 UTC, huacnlee commented on src/main.rs
> +        let path = &argv[1];
Why not to support multiple files?

2023-03-11 16:11 UTC, TheAwiteb commented on src/main.rs
> +        let path = &argv[1];
Ohh, nice idea. I'll work on it

2023-03-11 16:35 UTC, huacnlee requested changes

2023-03-11 16:35 UTC, huacnlee commented on src/main.rs
> +        // Format all files in the current directory
Else logic it not need, the for each part will handle that.

2023-03-14 13:57 UTC, TheAwiteb commented
Hi @huacnlee, can you explain the changes to be made

2023-03-15 02:45 UTC, closed without merging

2023-03-15 02:46 UTC, huacnlee commented
Hi @TheAwiteb I have make changes of why I mean and make a pull request again in #24